### PR TITLE
Show 'hours/minutes ago' for recent dates, fix timezone inconsistency in date handling

### LINKED ISSUE #1036: Show hours, minutes ago when last active date is today

### PR DESCRIPTION
**Pull request by Brainicism**
Closes #1036

### CODE REVIEW

File: src/helpers/utils.ts [hunk 1]
```diff
@@ -173,6 +173,17 @@ export function chooseWeightedRandom(list: Array<any>) {
  * @returns the date in yyyy-mm-dd format
```
Comment (taahamahdi) [inline src/helpers/utils.ts:173]: I think the function documentation needs to be updated

File: src/test/ci/leaderboard.test.ts [hunk 2]
```diff
@@ -20,10 +19,10 @@ const HOUR = 6;
 const MINUTE = 5;
 const INITIAL_SECONDS = 3;
 const date = new Date(new Date().getFullYear(), INITIAL_MONTH, INITIAL_DAY, HOUR, MINUTE, INITIAL_SECONDS);
-const secondAgo = new Date(date).setSeconds(INITIAL_SECONDS - 1);
-const yesterday = new Date(date).setDate(INITIAL_DAY - 1);
-const lastWeek = new Date(date).setDate(INITIAL_DAY - 7);
-const lastMonth = new Date(date).setMonth(INITIAL_MONTH - 1);
+const secondAgo = new Date(new Date(new Date(date).setSeconds(INITIAL_SECONDS - 1)));
```
Comment (taahamahdi) [inline src/test/ci/leaderboard.test.ts:22]: Is there an extra new Date here

**Review by taahamahdi — CHANGES_REQUESTED** [review]

File: src/test/ci/leaderboard.test.ts (hunk 2 above)
Comment (Brainicism) [reply src/test/ci/leaderboard.test.ts:22]: No, `.setSeconds, .setDate, setMonth` all return timestamp in ms

**Review by taahamahdi — APPROVED** [review]
