### PR TITLE
Replace broken patreon package with http call

### LINKED ISSUE #1324: Patreon fetch failing
Failed fetching patrons. err = TypeError: response.included is not iterable

### PR DESCRIPTION
**Pull request by Brainicism**
Closes #1324

### CODE REVIEW

File: src/helpers/patreon_manager.ts [hunk 1]
```diff
@@ -6,21 +6,78 @@ import type Patron from "../interfaces/patron";
...
+                };
+            };
+        };
+        type: string;
+    }>;
+
+    included: Array<{
+        attributes: {
+            social_connections: {
+                discord: {
```
Comment (taahamahdi) [inline src/helpers/patreon_manager.ts:36]: I think this can be null if the user hasn't linked a Discord account yet

File: src/helpers/patreon_manager.ts [hunk 2]
```diff
@@ -6,21 +6,78 @@ import type Patron from "../interfaces/patron";
...
+            logger.error(
+                `Couldn't find corresponding Patreon user for ${patreonMemberID}`
+            );
+            continue;
+        }
+
+        patrons.push({
+            discordID:
+                matchedPatreonUser.attributes.social_connections.discord
+                    .user_id,
```
Comment (taahamahdi) [inline src/helpers/patreon_manager.ts:70]: Similar here, either do a ?. or skip if there isn't a linked account yet

**Review by taahamahdi — CHANGES_REQUESTED** [review]

**Review by taahamahdi — APPROVED** [review]
