### PR TITLE
Fixed bug where multiple choice wouldn't decrement lives or end game in elimination

### LINKED ISSUE #937: Elimination doesn't work with ,answer
Guessing incorrectly doesn't decrement lives

### PR DESCRIPTION
**Pull request by taahamahdi**
Closes #937.

### CODE REVIEW

File: src/structures/game_session.ts [hunk 1]
```diff
@@ -259,6 +263,11 @@ export default class GameSession {
             this.endSession();
         } else if (this.scoreboard.gameFinished(guildPreference)) {
             this.endSession();
+        } else if (this.gameType === GameType.ELIMINATION) {
+            const eliminationScoreboard = this.scoreboard as EliminationScoreboard;
+            if (eliminationScoreboard.gameFinished()) {
```
Comment (Brainicism) [inline src/structures/game_session.ts:268]: Isn't this the same as line 265

**Review by Brainicism — CHANGES_REQUESTED** [review]

File: src/structures/game_session.ts (hunk 1 above)
Comment (taahamahdi) [reply src/structures/game_session.ts:268]: Since the subclass and superclass have different signatures I think I have to do this. Should I add guildPreferences as an unused argument to elimination scoreboard and remove these lines?

Comment (Brainicism) [reply src/structures/game_session.ts:268]: Let's do that

Comment (taahamahdi) [reply src/structures/game_session.ts:268]: Nevermind I'm wrong, I just tested it like you suggested and it works

**Review by Brainicism — APPROVED** [review]
