### PR TITLE
Fix inaccurate ranking when user is last place in any of the categories

### LINKED ISSUE #676: Profile rank is not accurate if player has more than 1 games played but 0 exp

### PR DESCRIPTION
**Pull request by Brainicism**
Closes #676

### CODE REVIEW

File: src/commands/game_commands/profile.ts [hunk 1]
```diff
@@ -84,29 +84,29 @@ export default class ProfileCommand implements BaseCommand {
...
-            .first())["count"];
+            .first())["count"] as number;
 
-        const relativeSongRank = ((await dbContext.kmq("player_stats")
+        const { exp, level } = (await dbContext.kmq("player_stats")
+            .select(["exp", "level"])
+            .where("player_id", "=", requestedPlayer.id)
+            .first());
+
+        const relativeSongRank = Math.max(((await dbContext.kmq("player_stats")
```
Comment (taahamahdi) [inline src/commands/game_commands/profile.ts:94]: Wouldn't this always pick totalPlayers as the maximum?

**Review by taahamahdi — CHANGES_REQUESTED** [review]

**Review by taahamahdi — APPROVED** [review]
