### PR TITLE
Fix minor formatting issues in round end, vote messages

### LINKED ISSUE #1106: Handle asterisks in song title and artist name
Screenshot from 2021-11-21 01-14-01

### PR DESCRIPTION
**Pull request by taahamahdi**
Closes #1106.

### CODE REVIEW

File: src/helpers/discord_utils.ts [hunk 1]
```diff
@@ -474,7 +474,7 @@ export async function sendEndRoundMessage(messageContext: MessageContext,
         color = EMBED_ERROR_COLOR;
     }
 
-    const songAndArtist = bold(`"${gameRound.originalSongName}" - ${gameRound.artistName}`);
+    const songAndArtist = bold(`"${gameRound.originalSongName}" - ${gameRound.artistName}`.split("*").join("\\*"));
```
Comment (Brainicism) [inline src/helpers/discord_utils.ts:477]: Should probably fix this at the source, in the implementation of `bold`, and our other formatting functions

**Review by Brainicism — APPROVED** [review]

File: src/helpers/discord_utils.ts (hunk 1 above)
Comment (Brainicism) [reply src/helpers/discord_utils.ts:477]: s

**Review by Brainicism — CHANGES_REQUESTED** [review]

File: src/helpers/discord_utils.ts (hunk 1 above)
Comment (Brainicism) [reply src/helpers/discord_utils.ts:477]: reset vote

**Review by Brainicism — CHANGES_REQUESTED** [review]

**Review by Brainicism — APPROVED** [review]
